### ISSUE TITLE
Error occurs when running the code 'demo.m'

### ISSUE THREAD

**Issue by hbyacademic** [janinethoma/image_navigation_matlab#1]
I have read the CVPR'2019 paper. It is impressed me a lot about formulating requirements for map building and localization and experiments do show the benefit from this such a map representation.  

Now, I have setup the same MATLAB toolbox and run on MATLAB R2017b, but some errors occur shown as follows. My working environment is Ubuntu 16.04. Is it the possible for making error when running under this environment?

```
Error using  - 
Matrix dimensions must agree.

Error in match_with_flow (line 11)
s = mean(sqrt(sum((ref_xy - t).^2, 1)));

Error in demo (line 117)
flow_matches = match_with_flow(query.xy,ref.xy(:,flow_lm),F(:,flow_lm),0);
```

**Comment by janinethoma** [comment]
Thank you for fixing this error in your pull request.
